# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad59e3da26f0d45dd1d9b75a11244d2dcb30fb7c8e7294a4f32a1127c61f1d05e21e4e9505aeb6fc6adc3a889d0069ea291ab42d10c5250639f630f1b6e80bd0

test:
  secret_key_base: 2ae84a409eec92c887c44bc5aa954605469687f0e8886e9c1ec96fc153bfac3e24640a93c1233dd6dcecb3701392cb67b8a7ddb4d049aac76d5020eb5fe46224

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
